apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: short-link
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - short-link
  selector:
    matchLabels:
      app: short-link
  endpoints:
    - port: http
      path: /metrics
      interval: 15s