name: short_link

services:
  db:
    image: postgres:18.1
    container_name: short_link-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=short_link
    volumes:
      - db_data:/var/lib/postgresql
  
  redis:
    image: redis:8-alpine
    container_name: short_link-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASS:-wsbmrc8PH18AIjID}
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: