// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createShortLink = `-- name: CreateShortLink :one
INSERT INTO links (id, original_url, created_at)
VALUES ($1, $2, NOW())
RETURNING id, original_url, created_at
`

type CreateShortLinkParams struct {
	ID          string
	OriginalUrl string
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createShortLink, arg.ID, arg.OriginalUrl)
	var i Link
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.CreatedAt)
	return i, err
}

const getShortLink = `-- name: GetShortLink :one
SELECT id, original_url, created_at
FROM links
WHERE id = $1
`

func (q *Queries) GetShortLink(ctx context.Context, id string) (Link, error) {
	row := q.db.QueryRow(ctx, getShortLink, id)
	var i Link
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.CreatedAt)
	return i, err
}
